export class BlogComments {
    constructor(
      public COMMENTID: number,
      public BLOGID: number,
      public TITLE: string,
      public DESCRIPTION: string,
      public SHORT_DESCRIPTION: string,
      public BLOG_IMAGE: string,
      public BLOG_IMAGE_FILEPATH: string,
      public BLOG_IMAGE_2: string,
      public BLOG_IMAGE_2_FILEPATH: string,
      public BLOG_IMAGE_3: string,
      public BLOG_IMAGE_3_FILEPATH: string,
      public CATEGORYID: number,
      public CATEGORY: string,
      public CATEGORY_ABBREVIATION: string,
      public CATEGORY_ICON: string,
      public CATEGORY_ICON_FILEPATH: string,
      public CATEGORY_IMAGE: string,
      public CATEGORY_IMAGE_FILEPATH: string,
      public ENTRYDATE: Date,
      public COMMENTS: string,
      public PARENT_COMMENTID: number,
      public PARENT_COMMENTS: string,
      public IPADDRESS: string,
      public USERAGENT: string,
      public STATUS: number,
      public APPROVED_BY: number,
      public APPROVER_USERNAME: string,
      public APPROVER_EMAILID: string,
      public APPROVER_USERROLE: string,
      public DONORID: number,
      public DONOR_USERNAME: string,
      public DONOR_EMAILID: string,
      public DONOR_PROFILE_IMAGE: string,
      public DONOR_PROFILE_IMAGE_FILEPATH: string,
      public ISPRIVATE: number,
      public USERID: number,
      public CMS_USERNAME: string,
      public CMS_EMAILID: string,
      public CMS_USERROLE: string,
      public ERROR: string
    ){
    }
}
