
export class Donorprofile {
    constructor(
        
        public AADHAAR_NUMBER:  string,
        public ADDITIONAL_INFO:  string,
        public ADDRESS_LINE_1: string,
        public ADDRESS_LINE_2: string,
        public ADDRESS_LINE_3: string,
        public CITY: string,
        public COMPANY_NAME:  string,
        public COUNTRY: string,
        public CREATEDBY: number,
        public DATEOFANNIVERSARY: Date,
        public DATEOFBIRTH: Date,
        public DONORID: number,
        public DONOR_PROFILE_IMAGE:  string,
        public DONOR_PROFILE_IMAGE_FILEPATH: string,
        public EMAILID: string,
        public EMPLOYMENT_PLACE:  string,
        public ENTRYDATE: Date,
        public ERROR:  string,
        public FACEBOOK:  string,
        public FIRSTNAME: string,
        public GENDER: string,
        public INCOME:  string,
        public IPADDRESS:  string,
        public ISPRIVATE: 1,
        public MOBILE: Number,
        public LASTNAME: string,
        public LINKEDIN:  string,
        public MARITAL_STATUS:  string,
        public MARRIAGE_DATE: Date,
        public NATIONALITY: string,
        public OCCUPATION:  string,
        public PAN_NUMBER:  string,
        public PHOTO:  string,
        public PINCODE: string,
        public PROFILEID: 2,
        public PASSWORD: string,
        public PROFILE_PRIVACY: false,
        public SKYPEID:  string,
        public SPOUSE_DATEOFBIRTH: Date,
        public SPOUSE_EMPLOYMENT_PLACE:  string,
        public SPOUSE_INCOME:  string,
        public SPOUSE_NAME:  string,
        public SPOUSE_OCCUPATION:  string,
        public STATE: string,
        public STATUS: string,
        public TELEPHONE: string,
        public TITLE: string,
        public TWITTER:  string,
        public USERAGENT:  string,
        public USERNAME: string,
    ) {

    }
}
