export class Donorsupporter {
    constructor(
        public PAYID: number,
        public ENTRYDATE: string,
        public PAYMENTID: string,
        public PAYMENTGATEWAYID: string,
        public DONORID: number,
        public DONOR_USERNAME: string,
        public DONOR_EMAILID: string,
        public ISPRIVATE: number,
        public DONOR_PROFILE_IMAGE: string,
        public DONOR_PROFILE_IMAGE_FILEPATH: string,
        public NEEDID: number,
        public NEED_NAME: string,
        public NEED_AMOUNT: string,
        public ADMINISTRATION_CHARGES: string,
        public PROJECTID: string,
        public BEGIN_DATE: Date,
        public END_DATE: Date,
        public PROJECT_BEGIN_DATE: Date,
        public PROJECT_END_DATE: Date,
        public FLAG: number,
        public NO_OF_DAYS_REQUIRED: number,
        public NEED_QUANTITY: number,
        public MODEOFPAYMENT: string,
        public TYPEOFPAYMENT: string,
        public IDENTIFICATIONNO: string,
        public CHEQUECARDDATE: string,
        public BANKNAME: string,
        public ACCOUNTNUMBER: string,
        public CHEQUECARDNAME: string,
        public EXPIRYMONTHYEAR: string,
        public PAYMENT_NEED_QUANTITY: number,
        public AMOUNT: string,
        public SOCIALHOURSDONATION: number,
        public ASSETSDESCRIPTION: string,
        public PAYMENTSTATUS: string,
        public IPADDRESS: string,
        public USERAGENT: string,
        public CREATEDBY: number,
        public ERROR: string
    ){

    }
}
