export class ImpactedLives {
    constructor(
        public IMPACTEDID : number,
        public ENTRYDATE : Date,
        public NEEDID : number,
        public NEED_NAME : string,
        public SECTORID : number,
        public SECTOR : string,
        public ABBREVIATION : string,
        public SECTOR_ICON : string,
        public SECTOR_ICONFILEPATH : string,
        public SECTOR_IMAGE : string,
        public SECTOR_IMAGEFILEPATH : string,
        public URL : string,
        public TITLE : string,
        public IMPACTED_LIVES_IMAGE_1_FILEPATH :string,
        public IMPACTED_LIVES_IMAGE_2_FILEPATH : string,
        public IMPACTED_ALT_IMAGE_TEXT: string,
        public DESCRIPTION : string,
        public SHORT_DESCRIPTION : string,
        public IMPACTED_LIVES_IMAGE : string,
        public IMPACTED_LIVES_IMAGEFILEPATH : string,
        public STATUS : string,
        public CREATEDBY : number,
        public ERROR : string,
        public SECTOR_SLUG : string,


       public DOCUMENTID : number,       
       public DOCUMENT_NAME : string,
       public DOCUMENT_TYPE : string,
       public DOCUMENT_TITLE : string,
       public DOCUMENT_URL_ACTUAL : string,
       public DOCUMENT_URL_ACTUAL_FILEPATH : string,
       public DOCUMENT_URL : string,
       public DOCUMENT_URL_FILEPATH : string,
       public DOCUMENT_URL_2 : string,
       public DOCUMENT_URL_2_FILEPATH : string,
       public DOCUMENT_URL_3 : string,
       public DOCUMENT_URL_3_FILEPATH : string,
       public DOCUMENT_URL_4 : string,
       public DOCUMENT_URL_4_FILEPATH : string,
       public DOCUMENT_URL_5 : string,
       public DOCUMENT_URL_5_FILEPATH : string,
       public DOCUMENT_URL_6 : string,
       public DOCUMENT_URL_6_FILEPATH : string,
       public DOCUMENT_URL_7 : string,
       public DOCUMENT_URL_7_FILEPATH : string,
       public DOCUMENT_URL_8 : string,
       public DOCUMENT_URL_8_FILEPATH : string,
       public DOCUMENT_URL_9 : string,
       public DOCUMENT_URL_9_FILEPATH : string,
       public APPROVED_BY : number,
       public APPROVED_BY_USERNAME : string,
       public APPROVED_BY_EMAILID : string,
       public APPROVED_BY_USERROLE : string,
       public APPROVED_DATE : Date,
       public APPROVED_STATUS : string,
       public IPADDRESS : string,
       public USERAGENT : string,
       public ISDEFAULT : number,
       public CREATED_BY_USERNAME : string,
       public CREATED_BY_EMAILID : string,
       public CREATED_BY_USERROLE : string
       
    ){}
}
