export class Needs {
    constructor(
        public RG_NEEDID : number,        
        public ADP_NEED_NAME : string,        
        public NEED_ADP_SHORT_DESCRIPTION: string,
        public NEED_THUMBNAIL_ACTUAL_IMAGE: string,        
        public NEED_THUMBNAIL_IMAGE_2: string,
        public NEED_THUMBNAIL_IMAGE_2_FILEPATH: string,
        public NEED_THUMBNAIL_IMAGE_3: string,
        public NEED_THUMBNAIL_IMAGE_3_FILEPATH: string,
        public NEED_THUMBNAIL_IMAGE_4_FILEPATH: string,
        public NEED_THUMBNAIL_IMAGE_5: string,
        public NEED_THUMBNAIL_IMAGE_5_FILEPATH: string,
        public NEED_THUMBNAIL_IMAGE_6: string,
        public NEED_THUMBNAIL_IMAGE_6_FILEPATH: string,
        public NEED_THUMBNAIL_IMAGE_7: string,
        public NEED_THUMBNAIL_IMAGE_7_FILEPATH: string,
        public NEED_THUMBNAIL_IMAGE_8: string,
        public NEED_THUMBNAIL_IMAGE_8_FILEPATH: string,
        public NEED_THUMBNAIL_IMAGE_9: string,
        public NEED_THUMBNAIL_IMAGE_9_FILEPATH: string,        
        public ADP_NAME: string,
        public ADP_CODE: string,        
        public SECTOR_SLUG: string,
        public SECTOR_ICON: string,
        public SECTOR_ICON_FILEPATH: string,        
        public NEEDTYPE_SLUG: string,
        public NEED_SUBTYPE: string,
        public NEEDTYPE_ABBREVIATION: string,
        public NEEDTYPE_ICON: string,
        public NEEDTYPE_ICON_FILEPATH: string,
        public NEEDTYPE_IMAGE: string,
        public NEEDTYPE_IMAGE_FILEPATH: string,
        public COLOR_CODES: string,        
        public SEQUENCE: number,
        public NO_OF_VILLAGES: number,
        public NEED_GENID: string,
        public DESIGNATIONID: string,
        public IS_CHILD_SPONSOR: number,
        public CHILDID: string,        
        public DONATION_AMOUNT: number,
        public TOTAL_DONORS: number,
        public TOTAL_NEED_AMOUNT: number,
        public DONATION_PERCENTAGE: number,
        public NEED_GROUP_FLAG: number,
        public GROUP_NEED_ID: number,
        public GROUP_NEED_NAME: string,
        public GROUP_ADP_NEED_NAME: string,
        public GROUP_NEED_TYPE: string,
        public GROUP_NEED_TYPE_SLUG: string,
        public MINIMUM_AMOUNT_PAYABLE: number,
        public ALLOW_SOCIAL_DONATION: number,
        public SHOW_IN_HOMEPAGE: number,
        public IS_MEGA_MENU: number,        
        public IMPRESSIONS: number,        
        public PAY_FREQUENCY: any,
        public NAME_OF_SHG: string,
        public NAME_OF_PERSON: string,        
        public ADP_LONGITUDE: string,
        public META_KEYWORD: string,
        public META_DESCRIPTION: string,
        public META_ROBOT: string,
        public META_CANONICAL: string,
        public DESIGNATIONTYPEID: number,
        public DESIGNATIONTYPE: string,
        public NEEDID: number,
        public ENTRYDATE: Date,
        public NEED_NAME: string,
        public NEED_DESCRIPTION: string,
        public NEED_SHORT_DESCRIPTION: string,
        public NEED_THUMBNAIL_IMAGE: string,
        public NEED_AMOUNT: number,
        public ADMINISTRATION_CHARGES: number,
        public COUNTRYID: number,
        public COUNTRY_NAME: string,
        public ADP_STATEID: number,
        public ADP_STATE_NAME: string,
        public ADP_DISTRICTID: number,
        public ADP_DISTRICT_NAME: string,
        public ADP_REGION: string,
        public SECTORID: number,
        public SECTOR: string,
        public CATEGORY: string,
        public NEEDTYPEID: number,
        public NEEDTYPE: string,
        public PROJECTID: string,
        public PAYMENT_FREQUENCY: string,
        public BEGIN_DATE: Date,
        public END_DATE: Date,
        public PROJECT_BEGIN_DATE: Date,
        public PROJECT_END_DATE: Date,
        public LATITUDE: string,
        public LONGITUDE: string,
        public NO_OF_DAYS_REQUIRED: number,
        public NEED_STATEID: number,
        public NEED_STATE_NAME: string,
        public NEED_DISTRICTID: number,
        public NEED_DISTRICT_NAME: string,
        public NEED_CITYID: number,
        public NEED_CITY_NAME: string,
        public BENEFICIARIES_COUNT: number,
        public VILLAGES: string,
        public COMMUNITY_DETAIL: string,  
        public ISDRAFT: number,
        public ISPUBLISHED: number,
        public DAYS_LEFT: number,
        public REMAINING_AMOUNT: number,
        public COMPLETED: string,
        public NEEDS_CHILD: any,
        public NEED_THUMBNAIL_ACTUAL_IMAGE_FILEPATH:string,
        public ADP_LATITUDE:string,
        public SHOW_IN_WEBSITE:number,
        public SHOW_IN_LANDINGPAGE:number,
        public STATUS: string,
        public ERROR: string,
        public IPADDRESS: string,
        public USERAGENT: string,        
        public ISRECURRING: number,
        public RECURRING_PERIOD: string,
        public NEED_QUANTITY_VALUES: any,
        public NEED_QUANTITY: number,
        public SEVERITY: string,
        public PRIORITY: string,
        public STATUS_INFORMATION: string,
        public FLAG: number,
        public BROCHURE: string,
        public BROCHUREFILEPATH: File,
        public NEED_THUMBNAIL_IMAGE_FILEPATH: File,
        public PMOID: number,
        public ADPID: number,
        public CREATEDBY: number,
        public TOTAL_NEED_AMOUNT_FOR_LARGE_NEED: number,
        public DONATION_AMOUNT_FOR_LARGE_NEED: number,
        public DAYS_LEFT_FOR_LARGE_NEED : number,
        public TOTAL_DONORS_FOR_LARGE_NEED : number,
        public needIdForFundraising : number,
        public PageSize : any

    ) { 
        
    }
}