export class Paymentresponse {
    constructor(
        public RESPONSEID: number,
        public ORDER_ID: string,
        public TRACKING_ID: string,
        public BANK_REF_NO: string,
        public ORDER_STATUS: string,
        public FAILURE_MESSAGE: string,
        public PAYMENT_MODE: string,
        public CARD_NAME: string,
        public STATUS_CODE: string,
        public STATUS_MESSAGE: string,
        public CURRENCY: string,
        public AMOUNT: string,
        public MERCHANT_PARAM1: string,
        public MERCHANT_PARAM2: string,
        public MERCHANT_PARAM3: string,
        public MERCHANT_PARAM4: string,
        public MERCHANT_PARAM5: string,
        public VAULT: string,
        public OFFER_TYPE: string,
        public OFFER_CODE: string,
        public RETRY: string,
        public RESPONSE_CODE: string,
        public MER_AMOUNT: number,
        public SUB_ACCOUNT_ID: string,
        public SI_CREATED: string,
        public SI_STATUS: string,
        public SI_REF_NO: string,
        public SI_SUB_REF_NO: string,
        public SI_MER_REF_NO: string,
        public SI_ERROR_DESC: string,
        public TRANS_DATE: string,
        public BIN_SUPPORTED: string,
        public BIN_COUNTRY: string,
        public DISCOUNT_VALUE: string,
        public ECI_VALUE: string,
        public TRANS_FEE: string,
        public SERVICE_TAX: string,
        public ENTRYDATE: Date,
        public TYPEOFPAYMENT: string,
        public PAY_ID: any
    ) {

    }
}