export class Smalldocument {
    constructor(
       public DOCUMENTID: number,
       public NEEDID: number,
       public NEED_NAME: string,
       public ENTRYDATE: Date,
       public DOCUMENT_NAME: string,
       public DOCUMENT_TYPE: string,
       public DOCUMENT_TITLE: string,
       public DOCUMENT_URL_ACTUAL: string,
       public DOCUMENT_URL_ACTUAL_FILEPATH: string,
       public DOCUMENT_URL: string,
       public DOCUMENT_URL_FILEPATH: string,
       public DOCUMENT_URL_2: string,
       public DOCUMENT_URL_2_FILEPATH: string,
       public DOCUMENT_URL_3: string,
       public DOCUMENT_URL_3_FILEPATH: string,
       public DOCUMENT_URL_4: string,
       public DOCUMENT_URL_4_FILEPATH: string,
       public DOCUMENT_URL_5: string,
       public DOCUMENT_URL_5_FILEPATH: string,
       public DOCUMENT_URL_6: string,
       public DOCUMENT_URL_6_FILEPATH: string,
       public DOCUMENT_URL_7: string,
       public DOCUMENT_URL_7_FILEPATH: string,
       public DOCUMENT_URL_8: string,
       public DOCUMENT_URL_8_FILEPATH: string,
       public DOCUMENT_URL_9: string,
       public DOCUMENT_URL_9_FILEPATH: string,
       public APPROVED_BY: number,
       public APPROVED_BY_USERNAME: string,
       public APPROVED_BY_EMAILID: string,
       public APPROVED_BY_USERROLE: string,
       public APPROVED_DATE: Date,
       public APPROVED_STATUS: string,
       public IPADDRESS: string,
       public USERAGENT: string,
       public STATUS: string,
       public CREATEDBY: number,
       public ISDEFAULT: number,
       public CREATED_BY_USERNAME: string,
       public CREATED_BY_EMAILID: string,
       public CREATED_BY_USERROLE: string,
       public ERROR: string
    ){}
}
